#!/bin/bash
# Default options
DIR="."
DEFAULT=false
BETA=false
XCODE_PATH="Xcode"
XCODE_PATH_PASSED=false

# Usage
USAGE="Usage: $0 [[-p|--path XCODE_PATH] | [-b|--beta] [-d|--default]]  [PATH]"

# Parse arguments
while [ $# -gt 0 ]
do
  key="$1"
  case $key in
    -h|--help)
    echo "$USAGE"
    exit
    ;;
    -d|--default)
    DEFAULT=true
    shift
    ;;
    -b|--beta)
    BETA=true
    shift
    ;;
    -p|--path)
    case "$2" in
      -h|--help|-d|--default|-b|--beta|"")
      echo "$USAGE"
      exit
      ;;
    esac
    XCODE_PATH=$2
    XCODE_PATH_PASSED=true
    shift 2
    ;;
    *)
    if [ $# -eq 1 ]; then
      DIR=$key
      shift
    else
      echo "$USAGE"
      exit 1
    fi
    ;;
  esac
done
shopt -s nullglob

FOUND=0
if [ $BETA = false ]; then
  if [ $DEFAULT = false ]; then
    APP="-a $XCODE_PATH"
  else
    if [ $XCODE_PATH_PASSED = false ]; then
      APP=""
    else
      echo "-d|--default and -p|--path flags both passed, ignoring the -d|--default flag"
    fi
  fi
else
  if [ $XCODE_PATH_PASSED = false ]; then
    APP="-a $XCODE_PATH-beta"
  else
    echo "-b|--beta and -p|--path flags both passed, ignoring the -b|--beta flag"
  fi
fi

# Try to open the first xcworkspace file found
EXT='xcworkspace'
for i in $DIR/*.$EXT; do
  open $APP "$i"
  FOUND=1
  break
done

# If nothing was found, try to open the first xcodeproj file found
if [ $FOUND -eq 0 ]; then
  EXT='xcodeproj'
  for i in $DIR/*.$EXT; do
    open $APP "$i"
    FOUND=1
    break
  done
fi

# If nothing was found, try to open the first Package.swift file found
if [ $FOUND -eq 0 ]; then
  if [ -f "$DIR/Package.swift" ]; then
    open $APP "Package.swift"
    FOUND=1
  fi
fi

shopt -u nullglob

# Print message if nothing was found
if [ $FOUND -eq 0 ]; then
  echo "No xcworkspace/xcodeproj/Package.swift file found in the specified directory."
  exit 1
fi
